apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
  #namespace: nginx
spec:
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

